<?php

namespace Shorty\FirstBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShortenedUrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShortenedUrlRepository extends EntityRepository
{
}
